#!/usr/bin/env node
// domain-map.mjs — deterministic step for /map-domain.
// Renders .harness/config.json#domains as a markdown doc with embedded
// mermaid graph + drift check against the filesystem.
//
// Usage:
//   domain-map.mjs [--out .harness/docs/architecture/domain-map.md]
//   domain-map.mjs --stdout

import { readFileSync, existsSync, writeFileSync, mkdirSync, statSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const ROOT = process.env.CLAUDE_PROJECT_DIR || process.cwd();

function parseArgs(argv) {
  const out = { outPath: null, stdout: false };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out") out.outPath = argv[++i];
    else if (argv[i] === "--stdout") out.stdout = true;
  }
  if (!out.outPath && !out.stdout) out.stdout = true;
  return out;
}

function loadConfig() {
  const p = resolve(ROOT, ".harness/config.json");
  if (!existsSync(p)) {
    console.error("domain-map: .harness/config.json not found at repo root");
    process.exit(2);
  }
  try { return JSON.parse(readFileSync(p, "utf8")); }
  catch (e) {
    console.error(`domain-map: .harness/config.json is not valid JSON: ${e.message}`);
    process.exit(2);
  }
}

function dirState(abs) {
  try {
    const st = statSync(abs);
    if (!st.isDirectory()) return "missing";
    const entries = readdirSync(abs);
    if (entries.length === 0) return "empty";
    return "present";
  } catch {
    return "missing";
  }
}

function driftBadge(state) {
  if (state === "present") return "✓";
  if (state === "empty") return "?";
  return "✗";
}

function safeId(s) {
  return String(s).replace(/[^a-zA-Z0-9_]/g, "_");
}

function buildMermaid(domains) {
  const lines = [];
  lines.push("```mermaid");
  lines.push("flowchart LR");
  let domainIdx = 0;
  const driftRows = [];
  for (const d of domains) {
    domainIdx++;
    const dName = d.name || `domain${domainIdx}`;
    const root = d.root || "";
    const layers = Array.isArray(d.layers) ? d.layers : [];
    const dId = safeId(dName);
    lines.push(`  subgraph ${dId} ["${dName} (${root}/)"]`);
    let prev = null;
    for (const layer of layers) {
      const abs = resolve(ROOT, root, layer);
      const state = dirState(abs);
      const badge = driftBadge(state);
      const node = `${dId}__${safeId(layer)}`;
      lines.push(`    ${node}["${layer} ${badge}"]`);
      if (prev) lines.push(`    ${prev} --> ${node}`);
      prev = node;
      driftRows.push({ domain: dName, layer, root, state, badge });
    }
    lines.push("  end");
  }
  lines.push("```");
  return { mermaid: lines.join("\n"), driftRows };
}

function buildMarkdown(cfg) {
  const domains = Array.isArray(cfg.domains) ? cfg.domains : [];
  const { mermaid, driftRows } = buildMermaid(domains);
  const drift = driftRows.filter((r) => r.state !== "present");
  const md = [];
  md.push(`# Domain map`);
  md.push("");
  md.push(`Generated by \`/map-domain\` from \`.harness/config.json\`. Re-run after editing domain/layer config.`);
  md.push("");
  md.push(`- domains: ${domains.length}`);
  md.push(`- layers (total): ${driftRows.length}`);
  md.push(`- drift entries: ${drift.length}`);
  md.push("");
  md.push(`## Diagram`);
  md.push("");
  md.push(mermaid);
  md.push("");
  md.push(`## Drift table`);
  md.push("");
  md.push(`| domain | layer | root | state | badge |`);
  md.push(`|---|---|---|---|---|`);
  for (const r of driftRows) {
    md.push(`| ${r.domain} | ${r.layer} | \`${r.root}/${r.layer}/\` | ${r.state} | ${r.badge} |`);
  }
  md.push("");
  if (drift.length > 0) {
    md.push(`## Resolutions`);
    md.push("");
    for (const d of drift) {
      if (d.state === "missing") {
        md.push(`- \`${d.root}/${d.layer}/\` is **missing**. Either create the directory (with a README.md) or remove "${d.layer}" from .harness/config.json#domains[${d.domain}].layers.`);
      } else if (d.state === "empty") {
        md.push(`- \`${d.root}/${d.layer}/\` exists but is empty. Add at least a README.md or seed file, or drop the layer from config.`);
      }
    }
    md.push("");
  }
  const tail = { domains: domains.length, layers: driftRows.length, drift_count: drift.length };
  md.push(`<!-- machine-tail: ${JSON.stringify(tail)} -->`);
  return { md: md.join("\n") + "\n", drift_count: drift.length };
}

function main() {
  const { outPath, stdout } = parseArgs(process.argv.slice(2));
  const cfg = loadConfig();
  const { md, drift_count } = buildMarkdown(cfg);
  if (outPath) {
    const abs = resolve(ROOT, outPath);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, md);
    process.stdout.write(JSON.stringify({ written: outPath, drift_count }) + "\n");
  }
  if (stdout) process.stdout.write(md);
}

main();
