#!/usr/bin/env bash
# PreToolUse hook (matcher: Edit|Write|MultiEdit|apply_patch) — denies direct edits to
# protected paths. Catches the failure mode where the agent decides to
# "just fix" a baseline file or .claude/ template instead of going through
# the proper /garbage-collection or scaffold-refresh paths.
#
# Protected paths (and why):
#   1. .claude/                         — skills, agents, hooks, settings.
#                                         Use /upgrade flow or edit the source
#                                         template in src/templates/.
#   2. node_modules/                    — package state, regenerated by install.
#   3. .git/                            — repo internals, never hand-edited.
#   4. .harness/structural-baseline.json — bypasses monotonic guard. Use the
#                                          /garbage-collection skill.
#   5. .harness/installed.json          — kit lockfile, derived from render.
#                                         Hand edits cause spurious "drift"
#                                         warnings on next upgrade.
#   6. .harness/state/advisor-runs/     — runtime proof written only by the
#                                         SubagentStop hook; hand edits let the
#                                         parent agent fake advisor delegation.
#
# Escape hatches:
#   - AHK_ALLOW_BYPASS=1 → log + allow (audit trail in .harness/bypass.log).
#   - AHK_HOOK_MODE=warn → log only, never deny.
set -eo pipefail

INPUT=$(cat)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
_LIB_DIR="$SCRIPT_DIR/_lib"
. "$_LIB_DIR/jp.sh"
if ! have_jp; then exit 0; fi

# Resolve target file. Write/Edit ship .tool_input.file_path; MultiEdit ships
# the same field at the top level. Both carry the absolute or repo-relative
# path. We normalise via Node to strip any leading ./ and use forward slashes.
FILE=""
if command -v node >/dev/null 2>&1; then
  FILE=$(node -e '
    const input = JSON.parse(process.argv[1] || "{}");
    const direct = input.tool_input?.file_path || input.tool_input?.path || input.tool_input?.file ||
      input.input?.file_path || input.input?.path || input.input?.file || input.file_path || input.path || "";
    if (direct) {
      process.stdout.write(String(direct));
      process.exit(0);
    }
    const patch = input.tool_input?.command || input.tool_input?.patch || input.command || input.patch || "";
    const targets = [
      ...String(patch || "").matchAll(/^\*\*\* (?:Add|Update|Delete) File: (.+)$/gm),
      ...String(patch || "").matchAll(/^\*\*\* Move to: (.+)$/gm),
    ]
      .map((match) => match[1].trim())
      .filter(Boolean);
    const protectedTarget = targets.find((value) =>
      /(^|\/)(?:\.claude|node_modules|\.git)\//.test(value) ||
      value === ".harness/structural-baseline.json" ||
      value === ".harness/installed.json" ||
      value.startsWith(".harness/state/advisor-runs/"),
    );
    process.stdout.write(String(protectedTarget || targets[0] || ""));
  ' "$INPUT" 2>/dev/null || true)
fi
if [ -z "$FILE" ]; then
  FILE=$(echo "$INPUT" | jp '.tool_input.file_path // empty')
fi
[ -z "$FILE" ] && exit 0

# Normalise to a path relative to CWD when possible; otherwise keep absolute.
REL_FILE="$FILE"
if [ -n "$PWD" ] && [[ "$FILE" == "$PWD"/* ]]; then
  REL_FILE="${FILE#"$PWD"/}"
fi
REL_FILE="${REL_FILE#./}"

REASON=""
case "$REL_FILE" in
  .claude/*|*/.claude/*)
    REASON=".claude/ is owned by the kit's scaffold. To change a skill/agent/hook, edit src/templates/.claude/ in the kit source and re-run 'agent-harness-kit upgrade', or override at the user level (~/.claude/)."
    ;;
  node_modules/*|*/node_modules/*)
    REASON="node_modules/ is regenerated by the package manager. Edit package.json or the upstream package; never hand-edit installed files."
    ;;
  .git/*|*/.git/*)
    REASON=".git/ contains repo internals. Use git commands ('git config', 'git update-ref', etc.) — never hand-edit."
    ;;
  .harness/structural-baseline.json)
    REASON="Direct edits to .harness/structural-baseline.json bypass the baseline-monotonic guard. Use the /garbage-collection skill or fix the underlying violation."
    ;;
  .harness/installed.json)
    REASON=".harness/installed.json is the kit lockfile, regenerated by 'agent-harness-kit init/upgrade'. Hand edits cause spurious drift warnings."
    ;;
  .harness/state/advisor-runs/*)
    REASON=".harness/state/advisor-runs/ is runtime proof written by the SubagentStop hook. Invoke the advisor subagent instead of hand-editing advisor proof."
    ;;
esac

if [ -z "$REASON" ]; then
  exit 0
fi

# Warn-only mode.
if [ "${AHK_HOOK_MODE:-}" = "warn" ]; then
  echo "[ahk] pretooluse-edit-guard (warn): would deny edit to $REL_FILE — $REASON" >&2
  exit 0
fi

# Bypass with audit log.
if [ "${AHK_ALLOW_BYPASS:-}" = "1" ]; then
  mkdir -p .harness
  TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  SHA=$(git rev-parse --short HEAD 2>/dev/null || echo 'no-git')
  ESCAPED=${REL_FILE//\"/\\\"}
  printf '{"ts":"%s","sha":"%s","bypass":"AHK_ALLOW_BYPASS","file":"%s","rule":"pretooluse-edit-guard"}\n' \
    "$TS" "$SHA" "$ESCAPED" >> .harness/bypass.log
  exit 0
fi

# Deny via JSON.
if command -v node >/dev/null 2>&1; then
  node -e "
    const reason = process.argv[1];
    const out = {
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: reason
      }
    };
    process.stdout.write(JSON.stringify(out));
  " "$REASON"
elif have_jq; then
  jq -nc --arg r "$REASON" \
    '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: $r}}'
else
  echo "$REASON" >&2
  exit 2
fi
exit 0
