#!/usr/bin/env node
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
const root=process.cwd(); const resultsRoot=resolve(root,'.harness/regression/results');
const args=process.argv.slice(2); const out=args.find(a=>a.startsWith('--out='))?.split('=')[1]||'.harness/regression/reports/regression-dashboard.html';
async function summaries(){ if(!existsSync(resultsRoot)) return []; const dirs=(await readdir(resultsRoot,{withFileTypes:true})).filter(d=>d.isDirectory()).map(d=>d.name).sort(); const arr=[]; for(const d of dirs){const p=join(resultsRoot,d,'summary.json'); if(existsSync(p)) arr.push(JSON.parse(await readFile(p,'utf8')));} return arr;}
const runs=await summaries(); const latest=runs.at(-1); const byVariant=new Map(runs.map(r=>[r.variant,r])); const variants=[...byVariant.values()].slice(-2);
const rows=(latest?.results||[]).map(r=>`<tr><td>${r.taskId}</td><td>${r.sessionIndex||1}</td><td>${r.failureClass}</td><td><span class="badge ${r.passed?'ok':'bad'}">${r.passed?'PASS':'FAIL'}</span></td><td>${r.durationMs}ms</td><td>$${r.costUSD.toFixed(4)}</td><td>${r.tokens.toLocaleString()}</td><td>${r.filesChanged.map(f=>`<code>${f}</code>`).join('<br>')}</td></tr>`).join('');
const failClasses={}; for(const r of latest?.results||[]) if(!r.passed) failClasses[r.failureClass]=(failClasses[r.failureClass]||0)+1;
const sessionRows=(latest?.multiSession?.sessions||[]).map(s=>`<tr><td>${s.sessionIndex}</td><td>${(s.passRate*100).toFixed(1)}%</td><td>${s.passed}/${s.total}</td><td>$${s.totalCostUSD.toFixed(4)}</td><td>${s.totalTokens.toLocaleString()}</td></tr>`).join('');
const taskRows=(latest?.multiSession?.tasks||[]).map(t=>`<tr><td>${t.taskId}</td><td>${(t.passRate*100).toFixed(1)}%</td><td>${t.passed}/${t.attempts}</td><td>${t.flaky?'<span class="badge bad">FLAKY</span>':'<span class="badge ok">STABLE</span>'}</td><td>${Math.round(t.avgDurationMs)}ms</td><td>${Math.round(t.avgTokens).toLocaleString()}</td></tr>`).join('');
const multi=latest?.multiSession?`<div class="card"><h2>Multi-session Stability</h2><div class="grid"><div class="metric"><div class="label">Sessions</div><div class="value">${latest.sessions||1}</div></div><div class="metric"><div class="label">Flaky Tasks</div><div class="value">${latest.multiSession.flakyTasks.length}</div></div><div class="metric"><div class="label">Quality Decay</div><div class="value">${(latest.multiSession.temporal.qualityDecay*100).toFixed(1)}%</div></div></div><h3>Session Distribution</h3><table><tr><th>Session</th><th>Pass Rate</th><th>Passed</th><th>Cost</th><th>Tokens</th></tr>${sessionRows}</table><h3>Task Stability</h3><table><tr><th>Task</th><th>Pass Rate</th><th>Passed</th><th>Stability</th><th>Avg Time</th><th>Avg Tokens</th></tr>${taskRows}</table></div>`:'';
const ab=variants.length===2?`<div class="card"><h2>A/B Comparison</h2><table><tr><th>Variant</th><th>Pass Rate</th><th>Cost</th><th>Tokens</th></tr>${variants.map(v=>`<tr><td>${v.variant}</td><td>${(v.passRate*100).toFixed(1)}%</td><td>$${v.totalCostUSD.toFixed(4)}</td><td>${v.totalTokens.toLocaleString()}</td></tr>`).join('')}</table></div>`:'';
const html=`<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><title>Regression Benchmark Dashboard</title><style>body{background:#09090b;color:#e4e4e7;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:32px}main{max-width:1200px;margin:auto}h1{font-size:40px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.card{background:#18181b;border:1px solid #27272a;border-radius:12px;padding:18px;margin:18px 0}.metric{background:#111113;border:1px solid #27272a;border-radius:12px;padding:16px}.value{font-size:32px;font-weight:800}.label{color:#a1a1aa}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #27272a;text-align:left;vertical-align:top}th{color:#a1a1aa}.badge{padding:4px 9px;border-radius:999px;font-weight:700;font-size:12px}.ok{background:#065f46;color:#d1fae5}.bad{background:#7f1d1d;color:#fecaca}code{background:#27272a;color:#fbbf24;padding:2px 4px;border-radius:4px}</style></head><body><main><h1>Tier 2 Regression Benchmark Dashboard</h1><p>Latest run: <code>${latest?.runId||'n/a'}</code></p><div class="grid"><div class="metric"><div class="label">Pass Rate</div><div class="value">${latest? (latest.passRate*100).toFixed(1):0}%</div></div><div class="metric"><div class="label">Passed</div><div class="value">${latest?.passed||0}/${latest?.total||0}</div></div><div class="metric"><div class="label">Cost</div><div class="value">$${(latest?.totalCostUSD||0).toFixed(4)}</div></div><div class="metric"><div class="label">Tokens</div><div class="value">${(latest?.totalTokens||0).toLocaleString()}</div></div><div class="metric"><div class="label">Interventions</div><div class="value">${latest?.interventions||0}</div></div></div>${ab}${multi}<div class="card"><h2>Top Failing Task Types</h2><pre>${Object.keys(failClasses).length?JSON.stringify(failClasses,null,2):'No failing task types'}</pre></div><div class="card"><h2>Task Results</h2><table><tr><th>Task</th><th>Session</th><th>Failure Class</th><th>Status</th><th>Time</th><th>Cost</th><th>Tokens</th><th>Files</th></tr>${rows}</table></div></main></body></html>`;
await mkdir(dirname(resolve(root,out)),{recursive:true}); await writeFile(out,html); console.log(out);
